version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tech_exercise_test
    ports:
      - 5432:5432
  server_test:
    build:
      dockerfile: Dockerfile.test
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=tech_exercise_test
