export const GET_SLOTS_REQUEST = 'GET_SLOTS_REQUEST';
export const GET_SLOTS_SUCCESS = 'GET_SLOTS_SUCCESS';
export const GET_SLOTS_FAILURE = 'GET_SLOTS_FAILURE';

export const SELECT_SLOT_REQUEST = 'SELECT_SLOT_REQUEST';
export const SELECT_SLOT_SUCCESS = 'SELECT_SLOT_SUCCESS';
export const SELECT_SLOT_FAILURE = 'SELECT_SLOT_FAILURE';

export const SELECT_SPECIAL_DELIVERY_REQUEST = 'SELECT_SPECIAL_DELIVERY_REQUEST';
export const SELECT_SPECIAL_DELIVERY_SUCCESS = 'SELECT_SPECIAL_DELIVERY_SUCCESS';
export const SELECT_SPECIAL_DELIVERY_FAILURE = 'SELECT_SPECIAL_DELIVERY_FAILURE';
